[package]
name = "kclvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "kclvm_cli_cdylib"

[[bin]]
path = "src/main.rs"
name = "kclvm_cli"

[build-dependencies]
cc = "1.0"

[dependencies]
clap = "3.2.22"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
glob = "0.3.0"
walkdir = "2"
libc = "0.2.112"
indexmap = "1.0"
fslock = "0.2.1"
libloading = "0.7.3"
chrono = "0.4.19"
threadpool = "1.0"

kclvm-ast = {path = "./ast", version = "0.1.0"}
kclvm-runner = {path = "./runner", version = "0.1.0"}
kclvm-parser = {path = "./parser", version = "0.1.0"}
kclvm-compiler = {path = "./compiler", version = "0.1.0"}
kclvm-config = {path = "./config", version = "0.1.0"}
kclvm-runtime = {path = "./runtime", version = "0.1.0"}
kclvm-sema = {path = "./sema", version = "0.1.0"}
kclvm-tools = {path = "./tools", version = "0.1.0"}
kclvm-version = {path = "./version", version = "0.1.0"}
kclvm-error = {path = "./error", version = "0.1.0"}
kclvm-query = {path = "./query", version = "0.1.0"}

[profile.release]
rpath = true
panic = "unwind"
opt-level = "z"  # Optimize for size.
lto = true

[workspace]
members = [
    "capi",
    "ast",
    "ast_pretty",
    "compiler",
    "config",
    "error",
    "lexer",
    "macros",
    "parser",
    "runner",
    "runtime",
    "sema",
    "span",
    "tools",
    "version",
    "query",
    "tools/src/kcl-language-server"
]
