[package]
name = "kclvm-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.0"
fancy-regex = "0.7.1"
walkdir = "2"
anyhow = "1.0"
tower-lsp = { version = "0.17.0"}

rustc_lexer = "0.1.0"
kclvm-ast = {path = "../ast", version = "0.1.0"}
kclvm-error = {path = "../error", version = "0.1.0"}
kclvm-parser = {path = "../parser", version = "0.1.0"}
kclvm-sema = {path = "../sema", version = "0.1.0"}
kclvm-config = {path = "../config", version = "0.1.0"}
kclvm-ast-pretty = {path = "../ast_pretty", version = "0.1.0"}
kclvm-query = {path = "../query", version = "0.1.0"}
kclvm-runner = {path = "../runner", version = "0.1.0"}

serde_json = "1.0.85"
serde_yaml = "0.9.13"
once_cell = "1.15.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false


